name: Terraform deployment

on:
  workflow-dispatch
    inputs:
      environment:
        description: choose environment
        type: choice
        options: [dev, test, prod]
        required: true
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: deployment to {{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform format
        run: terraform fmt -check -recursive

      - name: terraform init
        working-directory: environments/${{ inputs.environment }}
        run: terraform init

      - name: terraform validate
        working-directory: environments/${{ inputs.environment }}
        run: terraform validate

      - name: terraform plan
        id: plan
        working-directory: environments/${{ inputs.environment }}
        run: terraform plan

      - name: terraform apply
        working-directory: environments/${{ inputs.environment }}
        run: terraform apply --auto-approve

        

      