name: Terraform deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'choose environment (Dev, Stage, Prod)''
        type: choice
        options: [dev, test, prod]
        required: true

env:
  TF_VERSION: 1.6.0
  
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform--plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: terraform/environments/${{ github.event.inputs.environment }}
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform/environments/${{ github.event.inputs.environment }}
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: terraform/environments/${{ github.event.inputs.environment }}
        run: terraform plan -var-file=${{ github.event.inputs.environment }}.tfvars -out=tfplan
  
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: ${{ github.event.inputs.environment }}
    steps:     
      - name: terraform apply
        working-directory: terraform/environments/${{ github.event.inputs.environment }}
        run: terraform apply --auto-approve -var-file=${{ github.event.inputs.environment }}.tfvars



      