name: 3rd workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage
          - prod


jobs:
  test:
    name: test job
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "hi hello please"
  deploy:
    name: deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "this is deploy after test"
          echo "yes
          "

